defmodule FwdClient.Device do
  @moduledoc """
  Provides struct and type for a Device
  """
  use FwdClient.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          collectionError: String.t() | nil,
          displayName: String.t() | nil,
          managementIps: [String.t()] | nil,
          model: String.t() | nil,
          name: String.t() | nil,
          osVersion: String.t() | nil,
          platform: String.t() | nil,
          processingError: String.t() | nil,
          sourceName: String.t() | nil,
          type: String.t() | nil,
          vendor: String.t() | nil
        }

  defstruct [
    :__info__,
    :collectionError,
    :displayName,
    :managementIps,
    :model,
    :name,
    :osVersion,
    :platform,
    :processingError,
    :sourceName,
    :type,
    :vendor
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      collectionError:
        {:enum,
         [
           "NONE",
           "UNKNOWN",
           "CONNECTION_TIMEOUT",
           "PROMPT_DISCOVERY_FAILED",
           "CONNECTION_REFUSED",
           "AUTHENTICATION_FAILED",
           "KEY_EXCHANGE_FAILED",
           "AUTHORIZATION_FAILED",
           "AVI_SHELL_AUTH_FAILED",
           "AVI_CONTROLLER_WITHOUT_HEALTHY_SERVICE_ENGINES",
           "T128_CONDUCTOR_WITHOUT_HEALTHY_ROUTERS",
           "T128_CONFIG_ABSENT",
           "NETWORK_UNREACHABLE",
           "IO_ERROR",
           "SESSION_CLOSED",
           "SESSION_LIMIT_REACHED",
           "STATE_COLLECTION_FAILED",
           "PASSWORD_EXPIRED",
           "JUMP_SERVER_CONNECTION_TIMEOUT",
           "JUMP_SERVER_PASSWORD_AUTH_FAILED",
           "JUMP_SERVER_PASSWORD_EXPIRED",
           "JUMP_SERVER_CONNECTION_FAILED",
           "JUMP_SERVER_KEY_EXCHANGE_FAILED",
           "PROXY_SERVER_PING_FAILED",
           "PROXY_SERVER_PORT_REACHABILITY_FAILED",
           "PROXY_SERVER_CONNECTION_FAILED",
           "PROXY_SERVER_AUTHENTICATION_FAILED",
           "PRIV_PASSWORD_ERROR",
           "UNSUPPORTED_VERSION",
           "DEVICE_TYPE_UNDETECTED",
           "BMP_CONNECTION_FAILED",
           "BMP_CONNECTION_TIMEOUT",
           "BMP_COLLECTION_FAILED",
           "BMP_COLLECTION_TIMEOUT",
           "BMP_COLLECTION_REFUSED",
           "BMP_NOT_CONFIGURED",
           "BMP_CONFIGURED_WITH_LOCAL_IP",
           "WARN_TYPE_MISMATCH",
           "DEVICE_IS_CHILD_CONTEXT",
           "MANAGER_COLLECTOR_NOT_FOUND",
           "INCOMPLETE_SETUP",
           "COLLECTION_NOT_FOUND",
           "INFINITE_LOOP_IN_COMMAND_OUTPUT",
           "MISSING_FILE",
           "UNSUPPORTED_VENDOR",
           "COMMAND_DISABLED",
           "APIC_CONFIG_COLLECTION_FAILED",
           "UNEXPECTED_KEY_EXCHANGE_MESSAGE",
           "UNDISCOVERED_ACI_FABRIC",
           "SLOW_READ_RATE_DETECTED",
           "COLLECTION_TIMED_OUT",
           "COLLECTION_CANCELED",
           "OPERATION_TIMED_OUT",
           "CERTIFICATE_CHECK_FAILED",
           "DEVICE_IN_BAD_STATE",
           "PROJECT_VIEW_PERMISSION_MISSING",
           "NO_SPACE_LEFT_ON_COLLECTOR",
           "UNSUPPORTED_SSL_CONNECTION",
           "TACACS_SESSION_EXPIRED"
         ]},
      displayName: {:string, :generic},
      managementIps: [string: :generic],
      model: {:string, :generic},
      name: {:string, :generic},
      osVersion: {:string, :generic},
      platform:
        {:enum,
         [
           "unknown",
           "circuit",
           "l2_vpn_service",
           "missing_peer",
           "mpls_vpn_service",
           "internet_service",
           "intranet_service",
           "encryptor",
           "arista_eos",
           "avi_vantage",
           "bluecoat",
           "cisco_ios",
           "cisco_ios_xe",
           "cisco_ios_xr",
           "cisco_nxos",
           "cisco_asa",
           "cisco_ftd",
           "cisco_nxos_aci",
           "cisco_apic",
           "cisco_sg",
           "viptela",
           "viptela_smart",
           "juniper_junos",
           "juniper_srx",
           "juniper_netscreen",
           "linux_ovs_ofctl",
           "linux_os",
           "pica8_ovs_ofctl",
           "openflow_ovs",
           "f5",
           "a10_acos",
           "checkpoint",
           "hp_provision",
           "hp_comware",
           "fortinet",
           "pan_os",
           "esxi",
           "citrix_netscaler",
           "cumulus",
           "riverbed_steelhead",
           "riverbed_interceptor",
           "128t",
           "aruba_switch",
           "aruba_wifi_controller",
           "silver_peak_edgeconnect",
           "pensando",
           "cloud_genix",
           "forcepoint",
           "aws_cloud",
           "aws_subnet",
           "aws_rt",
           "aws_internet_gw",
           "aws_nat_gw",
           "aws_vpn_gw",
           "aws_direct_connect_gw",
           "aws_lb",
           "aws_global_accelerator",
           "aws_transit_gw",
           "aws_network_firewall",
           "aws_gateway_lb",
           "aws_service_endpoint",
           "nsx",
           "vcenter_api",
           "azure_cloud",
           "azure_subnet",
           "azure_vnet",
           "azure_vnet_gw",
           "azure_firewall",
           "azure_app_gw",
           "azure_lb",
           "azure_vwan_hub",
           "azure_vpn_gateway",
           "azure_p2s_vpn_gateway",
           "azure_express_route_gateway",
           "azure_virtual_appliance",
           "azure_express_route_circuit",
           "google_cloud",
           "gcp_rt",
           "gcp_subnet",
           "gcp_lb",
           "gcp_traffic_director",
           "gcp_vpn_gw",
           "gcp_nat_gw",
           "gcp_service_attachment",
           "avaya",
           "viasat_encryptor",
           "bluecat",
           "nokia",
           "versa_sase",
           "brocade_switch",
           "extreme_nos"
         ]},
      processingError:
        {:enum,
         [
           "LICENSE_EXHAUSTED",
           "MISSING_SIGNATURE",
           "DUPLICATE",
           "PARSER_EXCEPTION",
           "UNSUPPORTED_VENDOR"
         ]},
      sourceName: {:string, :generic},
      type:
        {:enum,
         [
           "UNKNOWN",
           "ROUTER",
           "SWITCH",
           "VSWITCH",
           "FIREWALL",
           "LOADBALANCER",
           "BUNDLED_ROUTER",
           "CIRCUIT",
           "L2_VPN_SERVICE",
           "MISSING_PEER",
           "MPLS_VPN_SERVICE",
           "INTERNET_SERVICE",
           "INTRANET_SERVICE",
           "SYNTHETIC_ENCRYPTOR",
           "HYPERVISOR",
           "CONTROLLER",
           "WAN_OPTIMIZER",
           "OPENFLOW_SWITCH",
           "SD_WAN",
           "RIVERBED_INTERCEPTOR",
           "WIFI_AP",
           "ENCRYPTOR",
           "DDI",
           "NIC",
           "AWS_CLOUD",
           "AWS_SUBNET",
           "AWS_RT",
           "AWS_INTERNET_GW",
           "AWS_NAT_GW",
           "AWS_VPN_GW",
           "AWS_LB",
           "AWS_GLOBAL_ACCELERATOR",
           "AWS_DIRECT_CONNECT_GW",
           "AWS_TRANSIT_GW",
           "AWS_NETWORK_FIREWALL",
           "AWS_GATEWAY_LB",
           "AWS_SERVICE_ENDPOINT",
           "EDGE_VM",
           "AZURE_CLOUD",
           "AZURE_SUBNET",
           "AZURE_VNET",
           "AZURE_VNET_GW",
           "AZURE_FIREWALL",
           "AZURE_APP_GW",
           "AZURE_LB",
           "AZURE_VWAN_HUB",
           "AZURE_VPN_GATEWAY",
           "AZURE_P2S_VPN_GATEWAY",
           "AZURE_EXPRESS_ROUTE_GATEWAY",
           "AZURE_VIRTUAL_APPLIANCE",
           "AZURE_EXPRESS_ROUTE_CIRCUIT",
           "GCP_CLOUD",
           "GCP_RT",
           "GCP_SUBNET",
           "GCP_LB",
           "GCP_TRAFFIC_DIRECTOR",
           "GCP_VPN_GW",
           "GCP_NAT_GW",
           "GCP_SERVICE_ATTACHMENT"
         ]},
      vendor:
        {:enum,
         [
           "UNKNOWN",
           "CISCO",
           "JUNIPER",
           "ARISTA",
           "PICA8",
           "F5",
           "A10",
           "CHECKPOINT",
           "HP",
           "FORTINET",
           "PALO_ALTO_NETWORKS",
           "VMWARE",
           "CITRIX",
           "CUMULUS",
           "RIVERBED",
           "OPENFLOW_GENERIC",
           "LINUX_GENERIC",
           "AMAZON",
           "SYMANTEC",
           "AVI_NETWORKS",
           "MICROSOFT",
           "GOOGLE",
           "AVAYA",
           "T128",
           "ARUBA",
           "VIASAT",
           "SILVER_PEAK",
           "PENSANDO",
           "FORCEPOINT",
           "BLUECAT",
           "NOKIA",
           "VERSA",
           "BROCADE",
           "EXTREME",
           "FORWARD_CUSTOM"
         ]}
    ]
  end
end
